<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <title>apreslebip</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="app.css" />
        <link href="https://fonts.googleapis.com/css?family=Arima+Madurai" rel="stylesheet" />
    </head>

    <body>
        <div id="app"></div>
        <script src="app.js"></script>
    </body>
</html>
